### ISSUE TITLE
Failed login in docker registry

### ISSUE THREAD

**Issue by jbcdnr** [epfml/kubernetes-setup#2]
```
docker login ic-registry.epfl.ch
```

returns error message:

```
Error response from daemon: Get https://ic-registry.epfl.ch/v2/: unauthorized: authentication required
```

I fixed it by specifying the version of the registry:

```
docker login ic-registry.epfl.ch/v1
```

@carlosperezepfl Should I update the `README` with this URL or the v2 default will be fine soon?

**Comment by carlosperezepfl** [comment]
Use  `  docker login ic-registry.epfl.ch  `
If you need to push or pull a private image, create a "robot" account. 

https://goharbor.io/docs/1.10/working-with-projects/project-configuration/create-robot-accounts/

Then configure the credentials store
https://docs.docker.com/engine/reference/commandline/login/

You need to specify the credentials store in $HOME/.docker/config.json

**Comment by jbcdnr** [comment]
Thank you.
I updated the README with instructions to use our robot credentials.
